#!/usr/bin/env ruby

$:.unshift(File.expand_path("../lib", __dir__))
require "sorbet/eraser"
require "sorbet/eraser/cli"

if ENV["BENCHMARK"]
  require "benchmark"
  Benchmark.bm do |x|
    x.report { Sorbet::Eraser::CLI.start(ARGV) }
  end
else
  Sorbet::Eraser::CLI.start(ARGV)
end
