name: Main

on:
- push
- pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.1'
        - '3.2'
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Test
      run: bundle exec rake test
